server:
  port: 8070
  tomcat:
    uri-encoding: UTF-8



logging:
  path: /var/logs/
  file: BookWorm_development.log
  config: classpath:config/logback-spring.xml
  level:
    root: DEBUG




spring:
  thymeleaf:
    prefix: classpath:/templates
    suffix: .html
    #html5
    mode: LEGACYHTML5
    cache: false
  #   mvc:
  #     view:
  #       perfix: classpath:/templates/web/jsp
  #       suffix: .jsp


  datasource:
    url: jdbc:mysql://23.105.193.183:3306/pro?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: 123456adsad
    #    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  #config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

    #securityconfig:
    #  logoutsuccessurl: /
    #  premitall: /rest/**,/bbs**
    #  deniedpage: /deny
    #  urlroles: /**/new = manage,amin;
    #           /**/edit/** = admin;
    #           /**/delete/** = admin
    
  
     
    
